name: Test Build on PR

on:
  pull_request:
    branches:
      - development
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: SENTRY_AUTH_TOKEN=${{secrets.SENTRY_AUTH_TOKEN}} yarn build